PUT http://localhost:8080/usuarios/d53789de-2f50-467e-b623-2abc3120f47c HTTP/1.1
content-type: application/json
Authorization: 5069ec07-ecb9-4440-87be-dd03da4c0021

{
    "nome": "Krabbe",
    "usuario": "jkrabbe",
    "senha": "123456"
}