POST http://localhost:8080/tweets/edefd123-f801-45d0-b951-861cc35add57 HTTP/1.1
Authorization: 8689c0ea-3d41-4162-a300-5e32b8234a4d
content-type: application/json

{
    "content": "teste1234",
    "type": "tweet"
}