POST http://localhost:8080/tweets/edefd123-f801-45d0-b951-861cc35add57 HTTP/1.1
Authorization: d8bd3cbb-c95a-478b-a483-d0664e8b5bab
content-type: application/json

{
    "content": "teste1234",
    "type": "tweet"
}